services:
  postgres:
    image: postgres:15
    container_name: slack-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slack_clone
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: slack-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  pg_data:
